### PR TITLE
Update Dockerfile to use new appsettings.docker.json file

### PR DESCRIPTION
**Pull request by alekratz**
Also, docker-compose.yml will map `./dbdata` to the MongoDB base data directory to keep the application persistent between deploys.

### CODE REVIEW

**Comment by alekratz** [comment]
Also, I plan to update the documentation - however, Github's wiki system isn't too great so I can't make a pull request directly. There are a few workarounds - [this solution](http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) seems the most integrated with the Github ecosystem, but requires some extra legwork.

**Comment by Wildcarde** [comment]
An alternative might be a github pages branch built into the branch list: https://pages.github.com/ (or a /docs folder)

**Comment by steffendx** [comment]
Thanks! Documentation would be great. I will take a look and check if I can get a new wiki repo up and running as described in the solution above. Wildcardes idea to use an integrated pages branch might work as well, but I guess it might not be as visible as using the wiki?

**Comment by alekratz** [comment]
From my experience, having a giant documentation header as one of the first things in the README is a good way to steer people in the right direction. e.g.

# [Documentation](#)

Of course, it's your project, so it's all up to you :)

**Pull request merged**
